### ISSUE TITLE
Sample/Component Bug (?): After several resizes, rendering sometimes stops

### ISSUE THREAD

**Issue by rrelyea** [Microsoft/WPFDXInterop#6]
After resizing your D3D11Image few times, it just stops rendering to it and thats all

[Originally filed by QuantumDeveloper as part of "D3DImage possible issues" https://github.com/Microsoft/WPFDXInterop/issues/2]

**Comment by rrelyea** [comment]
Believe that this is fixed with this changeset: https://github.com/Microsoft/WPFDXInterop/commit/ceae359edaedfe098c32571fb5db87900b413c82

**Comment by sqeezy** [comment]
I am pretty sure this is not resolved.
We just tested this with the nuget source and compiled the source ourselfes too.
Sometimes it needs a larger number of resizes but then it skips one OnRender call so that the the image is empty till the next frame is rendered. I'd like to see this issue reopened.
